name: Release webdav4

on:
  release:
    types: [published]
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: "1"

jobs:
  build-and-publish:
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
            python-version: 3.8

      - run: python -m pip install uv
      - run: uv pip install build
      - run: python -m build --installer=uv
      - if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
